name: Android Release + OTA

on:
  push:
    tags:
      - "v*"           # APK release trigger
    branches:
      - main           # OTA trigger
  workflow_dispatch: {} # manuel tetikleme için
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OTA_BRANCH: ${{ secrets.OTA_BRANCH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Keystore Decode
      - name: Decode Keystore
        if: startsWith(github.ref, 'refs/tags/v')  # Sadece APK release için
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore
      - name: Create gradle.properties for signing
        run: |
          cat >> android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=release.keystore
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF
      - name: Set up JDK
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Android SDK
        if: startsWith(github.ref, 'refs/tags/v')
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: "33.0.2"
          ndk: 23.1.7779620
      # Build APK
      - name: Build Release APK
        if: startsWith(github.ref, 'refs/tags/v')  # Sadece tag push
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --parallel --max-workers=8 --build-cache

      # Upload APK to GitHub Releases
      - name: Upload APK to Release
        if: startsWith(github.ref, 'refs/tags/v')  # Sadece tag push
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Install React Native CLI
        run: yarn add --dev @react-native-community/cli@latest
      - name: Install babel-plugin-module-resolver
        run: yarn add babel-plugin-module-resolver
      # OTA Update
      - name: Bundle React Native JS for OTA
        if: github.ref == 'refs/heads/main'  # sadece main branch push
        run: |
          mkdir -p ota
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output index.android.bundle \
            --minify true \
            --assets-dest ota
            --reset-cache

      - name: Upload OTA to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./ota
